### ISSUE TITLE
Blinking map during navigation [sometimes]

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#109]
During last weekend I was on Ukraine and used osmscout-sailfish. Sometimes map was blinking sometimes not. I think it's happens when there is something specific on the route. 
I tried it on Jolla 1 and Jolla C with the same result on the same routes.

https://www.dropbox.com/s/cwcgdb3p1ad5do3/20180505_081153.mp4?dl=0

**Comment by atlochowski** [comment]
it never happened to me before last update. If it will happen to me I will let you know.

**Comment by Karry** [comment]
Hi. 

I know about this issue. Osmscout needs to clear visual cache when route is recomputed. Problem is that navigation module is using route segments (direct line between junkctions) instead of real route. In case of wheezy roads with long route segments may be some positions on the route placed further from the segment than tolerance and route is re-cpmputed again and again... 

I plan to rewrite navigation module, but my time dedicated to this project is limited...

**Comment by Karry** [comment]
This problem should disappear with new release 1.0. Visual cache is invalidated without clearing now. See https://github.com/Framstag/libosmscout/pull/661 , these patches are included already in my SFOS branch that I am using for builds. 

The problem with the navigation still exists, but it is another story...
