### ISSUE TITLE
Allow custom download/import folder 

### ISSUE THREAD

**Issue by bonanza123** [Karry/osmscout-sailfish#14]
As far i know, currently the data is being downloaded to ~/Documents/maps. It would be nice to support user defined folders to allow e.g. a download and import from SD card.

**Comment by Karry** [comment]
Hi. Thanks for report. SD cards are mounted to `/media` subdirectories, right? This commit would detect it
https://github.com/Karry/osmscout-sailfish/commit/ec1393f737a5eec511cd0391a6edc8219f173dae

It will be possible to use this path for downloads then:

![sd card detection](https://cloud.githubusercontent.com/assets/309458/21419010/65d0959a-c825-11e6-9ddb-f06687a09087.png)

**Comment by bonanza123** [comment]
Thanks a lot, that's perfect!

**Comment by Karry** [comment]
Version 0.15 is released on OpenRepos ( https://openrepos.net/content/karry/osm-scout ), it will be available in Jolla Harbour soon. Please reopen this issue when it will not work for you. 

Thanks.

**Comment by Olf0** [comment]
Sorry, I originally posted this issue on Openrepos net, as I missed the link to Github: 
[With the update from OSM Scout Server 0.6.2 to 0.7.0, it became impossible to share the offline maps with OSM Scout (0.19 used; both installed from the Jolla Store) via their GUI-based settings.Both have fixed, incompatible directory names now, i.e. <chosen-OSMScoutServer-dirname>/osmscout for OSM Scout Server 0.7.0 and either \~/Documents/Maps or \<SDcard\>/Maps for OSM Scout.  Please implement a setting in OSM Scout to freely choose a directory for the offline maps or follow OSM Scout Server's map-directory settings scheme, and please do abandon the (limited) "~/Documents/Maps *or* \<SDcard\>/Map"-pulley.  The default may still be ~/Documents/Maps, although ~/OSMscout/osmscout may be a better location and is (already) compatible with OSM Scout Server 0.7.](https://openrepos.net/comment/17631#comment-17631)
Hence reopening this issue here.
