### ISSUE TITLE
option duplicated:  settings settings

### ISSUE THREAD

**Issue by GNUuser** [Karry/osmscout-sailfish#179]
![Captura_20191129_005](https://user-images.githubusercontent.com/45316884/69882148-40875d80-129d-11ea-9d7a-8e807409549e.png)

**Comment by GNUuser** [comment]
As you can see in the  screenshot there are 2 Ajustes. So it better to put the settings of map-online map-offline into the Units settings  like imperial, matrics, because it has better icons gear to a settings options.

**Comment by Karry** [comment]
Well, the first option is named "Map settings" in English and my idea was to have just map related options here. In the past, it was named "Layers". But then I renamed it, because it contains even label size, label font...

Second option is "Settings" in English. I was considering name it "Application settings", but I believe that it is unnecessarily long... Right now, it contains just units and coordinates format. But in the future, I want to add more options that are not related with the map rendering, but in other application functions. Like route recording, language of navigation commands...

Make it sense to you?

**Comment by GNUuser** [comment]
> Well, the first option is named "Map settings" in English and my idea was to have just map related options here. In the past, it was named "Layers". But then I renamed it, because it contains even label size, label font...
> 
> Second option is "Settings" in English. I was considering name it "Application settings", but I believe that it is unnecessarily long... Right now, it contains just units and coordinates format. But in the future, I want to add more options that are not related with the map rendering, but in other application functions. Like route recording, language of navigation commands...
> 
> Make it sense to you?

Yes make more sense, thank you karry
