### ISSUE TITLE
Bug in translation

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#18]
Hi
Can you tell where can I translate "Search" string? I translated everything but one string is still in English.
Screenshot: https://www.dropbox.com/s/5m79n0pzwhqhp09/Zrzut_ekranu_20161228_001.png?dl=0

**Comment by Karry** [comment]
Hi. I knew about this bug. I look at it closer and solution is simple: https://github.com/Karry/osmscout-sailfish/commit/43490e908bd0fe5cd8736be2e41835f8ad9d58cd 
translator have to be initialized before setting source to QML view...

It will be fixed in next release. Thanks for report, I needed get some impulse :)
