### ISSUE TITLE
Minor UI niggles

### ISSUE THREAD

**Issue by sbridger** [Karry/osmscout-sailfish#257]
Here are some minor UI niggles I have noticed...

When I press the menu button, I get the menu at the top, and map at the bottom.
Then when I select "Map" I get the map at the top, options page at the bottom.

It would probably be better to choose one convention and stick to it. ie items at the top, sub-map at the bottom.

---

I sort of expect the menu to be closed by dragging sideways, i.e. having the usual edge dot to the top.

Similarly, the "Map" page _is_ closed by dragging sideways, but it does not have the edge dot at the top that indicates this.

---
When I am on a function which has a sub-map i.e "navigation->to->pick a place"  or "map",  dragging the map drags the whole page  _when I drag along X_, closing the pick map page. If can drag the map around if I ensure my finger does not move on a staight horizontal line

You should make sure that page can only be closed by dragging the "cancel    accept" area which has the dot.
Within the map area dragging should just be panning the map

**Comment by Karry** [comment]
> ... 
> Then when I select "Map" I get the map at the top, options page at the bottom.
> It would probably be better to choose one convention and stick to it. ie items at the top, sub-map at the bottom.

The "Map" page had controls at the top previously as you described, but it was hard to touch controls with one hand on tall device like Jolla C (I was using it as my primary phone for years). When I was changing some option, my palm was covering preview map. And will be even worse on Xperia X II that has dimensions 157 x 69 mm. So I decided to break consistent UI and flip layout of this page - move map preview to the top and keep controls at the bottom (on portrait device orientation) or on the right (on landscape device orientation). I know that it is discrimination for left-hander people :-) 

On "place info" page problem is not so significant, because there is no so much interactive elements that you need to interact. And when you need to touch some button there, it is not problem that your palm is covering the map at the bottom.

I would like to have consistent UI and use common patterns used in SFOS, but just flip this page is not suitable IMHO. Maybe use similar layout as Gallery application using for editing images:

<img src="https://user-images.githubusercontent.com/309458/118239371-ff3b3b80-b499-11eb-9f22-d1e6ce93fcc1.png" width="200">

But it will be hard to do it properly, because Map page has more controls and horizontal scrolling have to be used. Current usage of "drawer" component is simple (just split screen to two parts).

> When I am on a function which has a sub-map i.e "navigation->to->pick a place" or "map", dragging the map drags the whole page when I drag along X, closing the pick map page. If can drag the map around if I ensure my finger does not move on a staight horizontal line
>
> You should make sure that page can only be closed by dragging the "cancel accept" area which has the dot.
Within the map area dragging should just be panning the map

I would like to do it that way, but I don't know how :-( Interesting is that Gallery application is able to handle it - you can move picture preview while editing image, and not to close dialog! It would be great to find the trick how to prevent Page component do it.

**Comment by Karry** [comment]
> You should make sure that page can only be closed by dragging the "cancel accept" area which has the dot.
> Within the map area dragging should just be panning the map

Finally, I was able to find the trick: https://github.com/Framstag/libosmscout/pull/1099
I will enable it in next release.

> Similarly, the "Map" page is closed by dragging sideways, but it does not have the edge dot at the top that indicates this.

I moved page header to the top, above the preview map. So, back "dot" indicator is visible...

**Comment by Karry** [comment]
Closing the issue, few UX issue was resolved. Please create new ticket or reopen this one if you found something for improvement.
