### ISSUE TITLE
Can't seem to 'Import' map data for offline use

### ISSUE THREAD

**Issue by physkets** [Karry/osmscout-sailfish#3]
App info states that to use offline maps, one may follow the instructions given [here](http://libosmscout.sourceforge.net/tutorials/Importing/).

I put the `.osm.pbf` file in the `Documents\Maps\` directory, but I don't understand how I can follow the rest of the instructions. There isn't any 'Import' folder anywhere on the phone, and what `build.sh` script?

Is it that the import feature hasn't been  integrated, or am I missing something?

**Comment by martonmiklos** [comment]
The import feature has not been integrated yet. The pbf file needs to be parsed on the host PC by the libosmscout binaries, and the resulting folders needs to be copied to the phone.

**Comment by physkets** [comment]
Ah! I see..  So when you say import feature, do you mean a feature where I can just put the pbf files in and the app will do the rest? And do you mean to say that I can currently do the parsing myself (on my computer) and copy it to the phone, and OSMScout will 'see' the files?  Or can I not even do this right now? I'm confused.

**Comment by martonmiklos** [comment]
I do not think that the pbf import feature would be ever integrated into the application because converting my countr ~93000 km^2 takes ~2 minutes on an i7 Intel CPU. 

What you can do now: 
Get a binary copy/compile of the libosmscout to your host PC:
https://github.com/Framstag/libosmscout

Grab a pbf file of your target region. 

Convert the pbf file on your desktop computer with the compiled/binary's Import executable as it is described here:
http://libosmscout.sourceforge.net/tutorials/Importing

Copy the contents of the resulted folder to your phone's Documents\Maps folder. (It will contain .idx and .dat files.)

This import method is known to be working with OSMScout 0.6.0.

**Comment by Karry** [comment]
@physkets : Yes, you should execute "Import process" on your computer and copy result to your phone. It can't be integrated to phone application, because for some maps - DACH for example (Germany, Austria, Switzerland) it takes almost 24 hours and require ~10 GB of RAM memory on computer...

I plan to deploy some download server and provide maps some europe countries in future. But my free time is limited and I am focusing to another features now...

**Comment by physkets** [comment]
Thanks a lot guys! I'm currently using an Arch based distro, and so do not have a lot of the dependencies required. An Ubuntu-14.04 that I have access to doesn't seem to satisfy the minimum cmake version required. I will see if I can upgrade the Ubuntu installation and try again.

**Comment by Karry** [comment]
Are you able to install Docker? You can start latest Ubuntu in Docker image... Or in some virtual image (KVM or VirtualBox)

**Comment by physkets** [comment]
Don't worry, I'll find a way and report here (if issue is still open).

**Comment by physkets** [comment]
Hey guys! It worked! I used a pbf from https://mapzen.com/data/metro-extracts/ because I only needed data for a city.

Is it possible to add data for two disjoint regions? Say two cities or two countries ?

**Comment by Karry** [comment]
Nice :-) So I will close this issue. 

To your question: currently only one map can be loaded. I know, it is limiting. I have this feature on my TODO list. But some things are higher...
