### ISSUE TITLE
No rendering of areas near map borders

### ISSUE THREAD

**Issue by Olf0** [Karry/osmscout-sailfish#52]
OSMscout 0.19.0 and 0.20.0 do not render a strip (of varying width from a few to \~ 50 km) along map borders. 
Additionally the rendering of the Netherlands from Castricum (in Noord-Holland) / Alkmaaar northeast-bound all along the north sea coast (until hitting the German border) is severely broken.  This may be linked to the first issue (as this also is along a map border). 
Note that Modrana with OSMscout Server does not exhibit either issue (with the same maps), but is unable to display more than a single map.  So while the whole map is displayed correctly in Modrana, one has to switch the map in OSMscout Server to peek across a (map) border.  Being able to display multiple offline maps (without switching) is basically a big plus for OSMscout, if only this feature would be working flawlessly. 
Tested on a Jolla 1 phone under SailfishOS 2.0.5 and 2.1.0 with maps (NL, LUX, DE; all dated 2017-03-27) for libosmscout downloaded with OSMscout Server's Map Manager.

**Comment by Karry** [comment]
Hi. I invest huge effort to improve rendering of map background (sea/land/unknown) last months : https://github.com/Framstag/libosmscout/pull/190

For profit from these changes, it is needed to upgrade everything: importer scripts (you should provide data polygon as input), importer (coastline computation was changed) and application (adapt map styles). 

You mention that you are using maps from @rinigus (author of OSM Scout server). These maps was most likely generated by Importer compiled without these patches (it was merged to upstream just a week ago). To solve your boundary problems, I suggest to download maps from OSM Scout or wait until @rinigus re-generate maps with latest Importer...

**Comment by Olf0** [comment]
@Karry: Thanks for the information.  And for your excellent software.
As the source of this issue seems to be clear, closing it.

**Comment by rinigus** [comment]
Hi folks,

while issue is closed, let me reply from the perspective of the server. I also have seen some disturbance next to the sea in OSM Scout when using OSM Scout Server maps. As @Karry pointed out, its probably due to incompatibilities in the imported format. @Karry has been working a lot on improving the import and getting support for import polygons in. Its surely an interesting step and I am looking forward to test it. Right now, I am busy with solving the rendering issues (multiple countries, world profile, labels and POI icons rendering, ...) using alternative approach - Mapnik - which works quite well. As a result, I couldn't spend much time on osmscout side of things, including testing. Which means that the update of the maps that I am planning within few days would be still with older osmscout import scripts and the library version.

As you could see, we frequently use slightly different versions of libosmscout in our programs. As a result, the incompatibilities between the maps should be expected. In the end, its due to the fast development of the library and we try to develop our programs as fast as we can to catch up with the requirements.

**Comment by Olf0** [comment]
@rinigus et al, retested today (2017-06-15) with OSM Scout 0.21 as well as OSM Scout Server 0.10.1 (using modRana as client), both using maps (dated 2017-06-04) downloaded with OSM Scout Server's Map-Manager: Working perfectly. :)
