### ISSUE TITLE
Main menu is always in English

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#86]
I uses osmscout with Polish language and main menu is in English but every submenu is in Polish.

**Comment by Karry** [comment]
Sorry for that, it was caused by renaming source file without rename translation context... See https://github.com/Karry/osmscout-sailfish/issues/87 for more details. Can you please translate few new phrases please? I will release it then... I was updating CMake build to keep translation files updated...

**Comment by atlochowski** [comment]
translation done
