### ISSUE TITLE
Issues on translation(es) in -v0.27.0

### ISSUE THREAD

**Issue by Caballlero** [Karry/osmscout-sailfish#87]

**Comment by Caballlero** [comment]
Osmscount main-page(only)  not ship spanish, Strange. Looks like translation folder need some clean & updates some word not appers to translate: Navigate may be  others too.

**Comment by Karry** [comment]
Ups. I missed it. It seems that translator is initialised after building first page, but this should not happen from first look to code... :-(

Thank you for report, I will investigate it at evening.

**Comment by Karry** [comment]
I found it, it was caused by renaming source file for main page from `Map.qml` to `MapPage.qml` - there was name conflict with file in different directory...  Because of that, translation context was changed. 

It is fixed by this commit:
https://github.com/Karry/osmscout-sailfish/commit/7297b2ed361b9e98e1157362d9bbcd05459884e1

Sorry for that, I miss it. Anyway, there was few missing phrases that was not included. Can you please take a look on it? I will release new version immediately.

**Comment by Caballlero** [comment]
Wait me  to send a new PR ,berore bump version. I need fix a ugly error on translation too :  )
